sudo: required

services:
  - docker

arch:
  script:
    - "sudo pacman -Sy"
    - "makepkg -si --noconfirm"
    - "sudo pacman -R overlayroot --noconfirm"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
